[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "faces"
version = "0.2"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src"
